#!/usr/bin/python
# -*- coding: utf8 -*-
#
# SWAML <http://swaml.berlios.de/>
# Semantic Web Archive of Mailing Lists
#
# This is just a wrapper script for the Buxon main Python program.
#
# Copyright (C) 2007-2008 Sergio Fernández
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

import sys

BUXON_PATH = '/usr/share/buxon/'
sys.path.append(BUXON_PATH)

try:
    from run import BuxonMain
    sys.exit(BuxonMain(sys.argv[1:], BUXON_PATH))
except ImportError:
    print 'Buxon cannot be found; please, ensure that it is installed correctly.'
    sys.exit(1)

