.TH BUXON "1" "December 2006" "buxon" "User Commands"
.SH NAME
\fBSWAML\fP \- SIOC forums browser
.SH SYNOPSIS
\fBbuxon\fP [uri]
.SH DESCRIPTION
\fBbuxon\fP is a SIOC forums browser, created by the SWAML 
developers as well and written in PyGTK.
.SH AUTHOR
Manpage written by Nacho Barrientos Arias <chipi@criptonita.com> and
Sergio Fdez <sergio@wikier.org> for the Debian GNU/Linux system (but
may be used by others).
.SH BUGS
Report bugs to Debian BTS or to http://swaml.berlios.de/bugs.
.SH COPYRIGHT
Copyright \(co 2006, Sergio Fdez. Licensed under GPLv2 license.
.PP
.nf
.fam C
http://swaml.berlios.de/
.SH "SEE ALSO"
.BR swaml (1)
