.TH BUXON "1" "March 2008" "buxon" "User Commands"
.SH NAME
\fBbuxon\fP \- RDF sioc:Forum browser
.SH SYNOPSIS
\fBbuxon\fP [uri]
.SH DESCRIPTION
\fBbuxon\fP is a RDF sioc:Forum browser, created by the SWAML 
developers as well and written in PyGTK.
.SH AUTHOR
Manpage written by Nacho Barrientos Arias <chipi@criptonita.com> and
Sergio Fernandez <sergio@wikier.org> for the Debian GNU/Linux system 
(but may be used by others).
.SH BUGS
Report bugs to http://swaml.berlios.de/bugs or to Debian BTS.
.SH COPYRIGHT
Copyright \(co 2006-2008, Sergio Fernandez. Licensed under GPLv2 license.
.PP
.nf
.fam C
http://swaml.berlios.de/
.SH "SEE ALSO"
.BR swaml (1)
